"""
Run the 4-mode Welch PSD injection study.

Loads synthetic H1+L1 data from injection_welch/ (generated by create_injection.py)
and runs nested sampling for each combination of:
  - likelihood model : norm  | alcs
  - PSD used         : true  | welch

Outputs (in --outdir):
    {mode}.csv
    {mode}_final_state.pkl

Usage:
    python blackjax_injection_welch.py [--injdir injection_welch] [--outdir injection_welch_results]
"""

import os
os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = "0.6"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"

import argparse
import jax
import jax.numpy as jnp
import numpy as np
import pickle
import tqdm
from anesthetic import NestedSamples
from blackjax.ns.utils import finalise

jax.config.update("jax_enable_x64", True)

from jimgw.single_event.detector import H1, L1
from jimgw.single_event.waveform import RippleIMRPhenomD
from custom_kernels import (
    acceptance_walk_sampler,
    create_unit_cube_functions,
    init_unit_cube_particles,
    transform_to_physical,
)

parser = argparse.ArgumentParser()
parser.add_argument('--injdir', default='injection_welch',
                    help='Directory containing injection .npy files')
parser.add_argument('--outdir', default='injection_welch_results',
                    help='Output directory for chains')
args = parser.parse_args()

os.makedirs(args.outdir, exist_ok=True)

# ---------------------------------------------------------------------------
# Load injection data
# ---------------------------------------------------------------------------
frequencies  = np.load(f'{args.injdir}/frequencies.npy')
psd_true_np  = np.load(f'{args.injdir}/psd_true.npy')
psd_welch_np = np.load(f'{args.injdir}/psd_welch.npy')
data_H1_np   = np.load(f'{args.injdir}/data_fd_H1.npy')
data_L1_np   = np.load(f'{args.injdir}/data_fd_L1.npy')
true_params  = np.load(f'{args.injdir}/true_params.npy', allow_pickle=True).item()

gmst = float(true_params['gmst'])

frequencies_jnp = jnp.array(frequencies, dtype=jnp.float64)
psd_true_jnp    = jnp.array(psd_true_np,  dtype=jnp.float64)
psd_welch_jnp   = jnp.array(psd_welch_np, dtype=jnp.float64)
data_H1_jnp     = jnp.array(data_H1_np,   dtype=jnp.complex128)
data_L1_jnp     = jnp.array(data_L1_np,   dtype=jnp.complex128)
mask_jnp        = jnp.ones(len(frequencies), dtype=jnp.float64)

print(f"Loaded injection data from {args.injdir}/")
print(f"  Frequencies: {frequencies[0]:.1f} – {frequencies[-1]:.1f} Hz  ({len(frequencies)} bins)")
print(f"  True params: M_c={true_params['M_c']:.2f}, q={true_params['q']:.2f}, "
      f"d_L={true_params['d_L']:.0f} Mpc")

waveform             = RippleIMRPhenomD(f_ref=20.0)
epoch                = 2       # post_trigger_duration = 2s → epoch = duration - 2
GH_X, GH_LOGW = (lambda x, w: (jnp.array(x), jnp.log(jnp.array(w))))(
    *np.polynomial.hermite.hermgauss(20))

# ---------------------------------------------------------------------------
# Per-bin likelihood kernels (identical to blackjax_gw_catalog.py)
# ---------------------------------------------------------------------------
def _norm_single_bin(B_i, log_S_i, log_two_df_over_pi):
    return log_two_df_over_pi - log_S_i - B_i * jnp.exp(-log_S_i)

def _alcs_single_bin(B_i, log_S_i, tau, log_two_df_over_pi):
    tau_sq = tau ** 2
    s0 = 0.5 * log_S_i
    s  = s0
    for _ in range(5):
        e2s = jnp.exp(-2.0 * s)
        f   = -2.0 + 2.0*B_i*e2s - (s - s0)/tau_sq
        fp  = -4.0*B_i*e2s - 1.0/tau_sq
        s   = s - f/fp
    H     = 4.0*B_i*jnp.exp(-2.0*s) + 1.0/tau_sq
    scale = jnp.sqrt(2.0 / H)
    s_nodes = s + scale * GH_X
    g_nodes = (-2.0*s_nodes - B_i*jnp.exp(-2.0*s_nodes)
               - (s_nodes - s0)**2 / (2.0*tau_sq))
    log_integral = jnp.log(scale) + jax.scipy.special.logsumexp(GH_LOGW + g_nodes + GH_X**2)
    return log_two_df_over_pi - 0.5*jnp.log(2.0*jnp.pi*tau_sq) + log_integral

# ---------------------------------------------------------------------------
# Prior parameter config
# ---------------------------------------------------------------------------
MC_TRUE = float(true_params['M_c'])
DL_TRUE = float(true_params['d_L'])

PARAM_CONFIG = {
    "M_c":     {"min": max(MC_TRUE*0.7, 1.0), "max": MC_TRUE*1.3, "prior": "uniform",     "wraparound": False},
    "q":       {"min": 0.125,                  "max": 1.0,          "prior": "uniform",     "wraparound": False},
    "s1_z":    {"min": -1.0,                   "max": 1.0,          "prior": "uniform",     "wraparound": False},
    "s2_z":    {"min": -1.0,                   "max": 1.0,          "prior": "uniform",     "wraparound": False},
    "iota":    {"min": 0.0,                    "max": jnp.pi,       "prior": "sine",        "wraparound": False},
    "d_L":     {"min": 100.0,                  "max": 10000.0,      "prior": "powerlaw",    "wraparound": False},
    "t_c":     {"min": -0.1,                   "max": 0.1,          "prior": "uniform",     "wraparound": False},
    "phase_c": {"min": 0.0,                    "max": 2*jnp.pi,     "prior": "uniform",     "wraparound": True},
    "psi":     {"min": 0.0,                    "max": jnp.pi,       "prior": "uniform",     "wraparound": True},
    "ra":      {"min": 0.0,                    "max": 2*jnp.pi,     "prior": "uniform",     "wraparound": True},
    "dec":     {"min": -jnp.pi/2,              "max": jnp.pi/2,     "prior": "cosine",      "wraparound": False},
    "tau":     {"min": 0.001,                  "max": 2.0,          "prior": "log_uniform", "wraparound": False},
}

def get_ravel_order(particles_dict):
    test_dict = {key: float(i) for i, key in enumerate(particles_dict.keys())}
    test_flat, _ = jax.flatten_util.ravel_pytree(test_dict)
    order = []
    for val in test_flat:
        for key, test_val in test_dict.items():
            if abs(val - test_val) < 1e-10:
                order.append(key)
                break
    return order

# ---------------------------------------------------------------------------
# Run one (likelihood_model, psd_label) combination
# ---------------------------------------------------------------------------
def run_one_mode(likelihood_model, psd_label):
    """
    likelihood_model : 'norm' or 'alcs'
    psd_label        : 'true' or 'welch'
    """
    mode_name = f"{likelihood_model}_{psd_label}"
    use_alcs  = likelihood_model == 'alcs'
    psd_jnp   = psd_true_jnp if psd_label == 'true' else psd_welch_jnp

    base_keys   = ["M_c","q","s1_z","s2_z","iota","d_L","t_c","psi","ra","dec","phase_c"]
    sample_keys = base_keys + (["tau"] if use_alcs else [])

    test_particles = {key: jax.random.uniform(jax.random.PRNGKey(42), (100,))
                      for key in sample_keys}
    sample_keys = get_ravel_order(test_particles)

    sc = {key: PARAM_CONFIG[key] for key in sample_keys}

    param_mins = jnp.array([sc[k]["min"] for k in sample_keys])
    param_maxs = jnp.array([sc[k]["max"] for k in sample_keys])
    param_prior_types = jnp.array([
        0 if sc[k]["prior"] == "uniform"     else
        1 if sc[k]["prior"] == "sine"        else
        2 if sc[k]["prior"] == "cosine"      else
        3 if sc[k]["prior"] == "powerlaw"    else
        4 for k in sample_keys
    ])

    @jax.jit
    def prior_transform_fn(u_params):
        u, _ = jax.flatten_util.ravel_pytree(u_params)
        x = jnp.where(param_prior_types == 0, param_mins + u*(param_maxs-param_mins),
            jnp.where(param_prior_types == 1, jnp.arccos(1 - 2*u),
            jnp.where(param_prior_types == 2, jnp.arcsin(2*u - 1),
            jnp.where(param_prior_types == 3,
                      (param_mins**3 + u*(param_maxs**3 - param_mins**3))**(1/3),
                      param_mins*(param_maxs/param_mins)**u))))
        _, unflatten = jax.flatten_util.ravel_pytree({k: 0.0 for k in sample_keys})
        return unflatten(x)

    # Detector data and PSD injected inline (no jimgw load_data)
    det_data = [
        {'name': 'H1', 'data': data_H1_jnp, 'psd': psd_jnp,
         'fd_response': H1.fd_response},
        {'name': 'L1', 'data': data_L1_jnp, 'psd': psd_jnp,
         'fd_response': L1.fd_response},
    ]

    def loglikelihood_fn(params):
        p = dict(params)
        p["gmst"] = gmst
        p["eta"]  = p["q"] / (1 + p["q"])**2
        waveform_sky   = waveform(frequencies_jnp, p)
        align_time     = jnp.exp(-1j*2*jnp.pi*frequencies_jnp*(epoch + p["t_c"]))
        df             = frequencies_jnp[1] - frequencies_jnp[0]
        log_two_df_over_pi = jnp.log(2.0*df/jnp.pi)
        log_L = 0.0
        for det in det_data:
            h    = det['fd_response'](frequencies_jnp, waveform_sky, p) * align_time
            B    = 2.0*df * jnp.abs(det['data'] - h)**2
            logS = jnp.log(det['psd'])
            if use_alcs:
                bins = jax.vmap(lambda b, ls: _alcs_single_bin(
                    b, ls, p["tau"], log_two_df_over_pi))(B, logS)
            else:
                bins = jax.vmap(lambda b, ls: _norm_single_bin(
                    b, ls, log_two_df_over_pi))(B, logS)
            log_L = log_L + jnp.sum(bins * mask_jnp)
        return log_L

    n_live   = 1400
    n_delete = 700
    rng_key  = jax.random.PRNGKey(10)
    rng_key, init_key = jax.random.split(rng_key)

    example_params      = {key: 0.0 for key in sample_keys}
    unit_cube_particles = init_unit_cube_particles(init_key, example_params, n_live)

    periodic_mask = jax.tree_util.tree_map(lambda _: False, example_params)
    for key in sample_keys:
        if sc[key]["wraparound"]:
            periodic_mask[key] = True

    unit_cube_fns = create_unit_cube_functions(
        physical_loglikelihood_fn=loglikelihood_fn,
        prior_transform_fn=prior_transform_fn,
        mask_tree=periodic_mask,
    )

    nested_sampler = acceptance_walk_sampler(
        logprior_fn=unit_cube_fns['logprior_fn'],
        loglikelihood_fn=unit_cube_fns['loglikelihood_fn'],
        nlive=n_live, n_target=60, max_mcmc=5000, num_delete=n_delete,
        stepper_fn=unit_cube_fns['stepper_fn'],
    )
    state = nested_sampler.init(unit_cube_particles)

    @jax.jit
    def one_step(carry, xs):
        state, k = carry
        k, subk = jax.random.split(k)
        state, dead_point = nested_sampler.step(subk, state)
        return (state, k), dead_point

    def terminate(state):
        dlogz = jnp.logaddexp(0, state.logZ_live - state.logZ)
        return jnp.isfinite(dlogz) and dlogz < 0.1

    dead = []
    with tqdm.tqdm(desc=f"{mode_name}", unit=" dead points") as pbar:
        while not terminate(state):
            (state, rng_key), dead_info = one_step((state, rng_key), None)
            dead.append(dead_info)
            pbar.update(n_delete)

    final_state = finalise(state, dead)
    physical_particles = transform_to_physical(final_state.particles, prior_transform_fn)
    logL_birth = jnp.where(jnp.isnan(final_state.loglikelihood_birth),
                            -jnp.inf, final_state.loglikelihood_birth)

    column_to_label = {
        "M_c": r"$\mathcal{M}_c$", "q": r"$q$", "d_L": r"$d_L$",
        "iota": r"$\iota$", "ra": r"$\alpha$", "dec": r"$\delta$",
        "s1_z": r"$\chi_1$", "s2_z": r"$\chi_2$", "t_c": r"$t_c$",
        "psi": r"$\psi$", "phase_c": r"$\phi_c$", "tau": r"$\tau$",
    }

    samples = NestedSamples(
        physical_particles, logL=final_state.loglikelihood,
        logL_birth=logL_birth, labels=column_to_label,
        logzero=jnp.nan, dtype=jnp.float64,
    )

    out = os.path.join(args.outdir, mode_name)
    samples.to_csv(f"{out}.csv")
    with open(f"{out}_final_state.pkl", "wb") as f:
        pickle.dump(final_state, f)
    print(f"  Saved {out}.csv   logZ = {samples.logZ():.2f}")

# ---------------------------------------------------------------------------
# Run all four combinations
# ---------------------------------------------------------------------------
MODES = [
    ('norm', 'true'),
    ('norm', 'welch'),
    ('alcs', 'true'),
    ('alcs', 'welch'),
]

for likelihood_model, psd_label in MODES:
    print(f"\n{'='*60}")
    print(f"  likelihood={likelihood_model}  PSD={psd_label}")
    print(f"{'='*60}")
    run_one_mode(likelihood_model, psd_label)
